spring:
  application:
    name: final
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=sample1;encrypt=false; # change it if necessary
    username: sa
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  graphql:
    graphiql:
      enabled: true
  web:
    resources:
      static-locations: classpath:/static/
server:
  port: 9005

junit:
  jupiter:
    execution:
      parallel:
        enabled: true
        mode:
          default: concurrent

grpc:
  server:
    port: 9006
